default:
  image: hpiicpc/problem-list-builder:latest


variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'


build:
  stage: build
  only:
    - master
  artifacts:
    expire_in: 7 days
    paths:
      - build
  cache:
    paths:
      - .cache
  before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.hpi.de/competitive-programming/problem-list.git
    - pip3 install -r tools/requirements.txt
    - pip3 install -r problem-list/requirements.txt
  script:
    - ./problem-list/ci-cache-setup.py
    - ./problem-list/generate.py . build "${CI_PROJECT_URL}"
    - ./problem-list/ci-cache-teardown.py


deploy:
  stage: deploy
  only:
    - master
  script:
    # Add known host entries for our deploy server
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$DEPLOY_SERVER_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # Add ssh deploy key
    - echo "$DEPLOY_SSH_KEY" > deploy-key
    - chmod 600 deploy-key
    # This relies on the CI server also being in the HPI network so that it can actually reach this ip
    - rsync -az --delete -e "ssh -i deploy-key" build/ problem-list-deploy@172.20.9.3:/opt/problem-list/static
